// Verse-of-the-day pool (KJV, public domain) — rotates deterministically by day of year.
export const VERSES = [
    {ref:'Joshua 1:9', tag:'challenging', text:"Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."},
    {ref:'Isaiah 41:10', tag:'inspiring', text:"Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness."},
    {ref:'Philippians 4:13', tag:'inspiring', text:"I can do all things through Christ which strengtheneth me."},
    {ref:'Proverbs 3:5-6', tag:'challenging', text:"Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths."},
    {ref:'Romans 8:28', tag:'inspiring', text:"And we know that all things work together for good to them that love God, to them who are the called according to his purpose."},
    {ref:'Jeremiah 29:11', tag:'inspiring', text:"For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end."},
    {ref:'Psalm 46:1', tag:'inspiring', text:"God is our refuge and strength, a very present help in trouble."},
    {ref:'2 Timothy 1:7', tag:'challenging', text:"For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."},
    {ref:'Isaiah 40:31', tag:'inspiring', text:"But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."},
    {ref:'Matthew 6:33', tag:'challenging', text:"But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."},
    {ref:'Galatians 6:9', tag:'challenging', text:"And let us not be weary in well doing: for in due season we shall reap, if we faint not."},
    {ref:'Psalm 27:1', tag:'inspiring', text:"The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?"},
    {ref:'1 Corinthians 16:13', tag:'challenging', text:"Watch ye, stand fast in the faith, quit you like men, be strong."},
    {ref:'Deuteronomy 31:6', tag:'inspiring', text:"Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee."},
    {ref:'James 1:22', tag:'challenging', text:"But be ye doers of the word, and not hearers only, deceiving your own selves."},
    {ref:'Romans 12:2', tag:'challenging', text:"And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God."},
    {ref:'Luke 9:23', tag:'challenging', text:"And he said to them all, If any man will come after me, let him deny himself, and take up his cross daily, and follow me."},
    {ref:'2 Corinthians 5:17', tag:'inspiring', text:"Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new."},
    {ref:'Hebrews 11:1', tag:'inspiring', text:"Now faith is the substance of things hoped for, the evidence of things not seen."},
    {ref:'Micah 6:8', tag:'challenging', text:"He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?"},
    {ref:'Zephaniah 3:17', tag:'inspiring', text:"The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing."},
    {ref:'John 3:16', tag:'inspiring', text:"For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."},
    {ref:'Psalm 23:1', tag:'inspiring', text:"The LORD is my shepherd; I shall not want."}
  ];